export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const SELECT_METRIC = "SELECT_METRIC";
export const GET_HEARTBEAT = "GET_HEARTBEAT";
export const GET_MEASUREMENTS = "GET_MEASUREMENTS";